default_platform(:ios)

platform :ios do
  before_all do
    ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '1'
  end

  desc 'Run unit tests'
  lane :unit_test do
    scan(
      scheme: 'ChecklistsUnitTest',
      code_coverage: true
    )
    xcov(
      scheme: 'ChecklistsUnitTest',
      minimum_coverage_percentage: 20.00,
      only_project_targets: true
    )
  end

  desc 'Run Local UI tests'
  lane :ui_test_local do
    scan(scheme: 'ChecklistsUITestLocal')
  end

  desc 'Run Integration UI tests'
  lane :ui_test_integration do
    scan(scheme: 'ChecklistsUITestIntegration')
  end
end
