default_platform(:ios)

platform :ios do
  desc 'Run unit tests'
  lane :unit_test do
    scan(scheme: 'ChecklistsUnitTest')
  end

  desc 'Run UI tests'
  lane :ui_test do
    scan(scheme: 'ChecklistsUITest')
  end
end